### ISSUE TITLE
User can add an entry

### ISSUE THREAD

**Issue by rachelbeacham** [rachelbeacham/weekly-planner#1]
##  Feature

User can add an entry to the planner

## 📐 Plan

When the user clicks the "Add Entry" button the Add Entry modal appears.  After the entry is saved the modal is hidden again.

## 🖼️ Wireframe

![Screen Shot 2021-02-02 at 2 33 47 PM](https://user-images.githubusercontent.com/68713535/107302187-cf5f4080-6a31-11eb-8582-8e11efe53330.png)

## ✅ Task List

- [x] Pick a nice font pair from Google Fonts for headings and body text.
- [x] Pick a nice accent color.
- [x] Pick a background image.
- [x] Add an add entry button
- [x] Style add entry button
- [x] Create a component for the add entry modal
- [x] Style modal
- [ ] Add a handleclick method for the add entry button
- [ ] Update render method to show modal based on state
